# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1388, 676)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 181, 581))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.leaf_button_2 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_2.setGeometry(QtCore.QRect(10, 80, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_2.setFont(font)
        self.leaf_button_2.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/security-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_2.setIcon(icon)
        self.leaf_button_2.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_2.setObjectName("leaf_button_2")
        self.leaf_button_3 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_3.setGeometry(QtCore.QRect(10, 200, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_3.setFont(font)
        self.leaf_button_3.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/number.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_3.setIcon(icon1)
        self.leaf_button_3.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_3.setObjectName("leaf_button_3")
        self.leaf_button_4 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_4.setGeometry(QtCore.QRect(10, 260, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_4.setFont(font)
        self.leaf_button_4.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/seo-report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_4.setIcon(icon2)
        self.leaf_button_4.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_4.setObjectName("leaf_button_4")
        self.leaf_button_5 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_5.setGeometry(QtCore.QRect(10, 320, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_5.setFont(font)
        self.leaf_button_5.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/user (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_5.setIcon(icon3)
        self.leaf_button_5.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_5.setObjectName("leaf_button_5")
        self.leaf_button_6 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_6.setGeometry(QtCore.QRect(10, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_6.setFont(font)
        self.leaf_button_6.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_6.setIcon(icon4)
        self.leaf_button_6.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_6.setObjectName("leaf_button_6")
        self.leaf_button_7 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_7.setGeometry(QtCore.QRect(10, 140, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_7.setFont(font)
        self.leaf_button_7.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_7.setIcon(icon5)
        self.leaf_button_7.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_7.setObjectName("leaf_button_7")
        self.leaf_button_8 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_8.setGeometry(QtCore.QRect(10, 440, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_8.setFont(font)
        self.leaf_button_8.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_8.setIcon(icon6)
        self.leaf_button_8.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_8.setObjectName("leaf_button_8")
        self.leaf_button_9 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_9.setGeometry(QtCore.QRect(10, 20, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_9.setFont(font)
        self.leaf_button_9.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_9.setIcon(icon7)
        self.leaf_button_9.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_9.setObjectName("leaf_button_9")
        self.leaf_button_10 = QtWidgets.QPushButton(self.frame)
        self.leaf_button_10.setGeometry(QtCore.QRect(10, 500, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_10.setFont(font)
        self.leaf_button_10.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        self.leaf_button_10.setIcon(icon6)
        self.leaf_button_10.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_10.setObjectName("leaf_button_10")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 1261, 71))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(250, 0, 841, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 255, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 80, 1071, 571))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_17.setObjectName("label_17")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1051, 491))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plate_txt_label = QtWidgets.QLabel(self.tab)
        self.plate_txt_label.setGeometry(QtCore.QRect(30, 50, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.plate_txt_label.setFont(font)
        self.plate_txt_label.setStyleSheet("color: rgb(0, 255, 0);")
        self.plate_txt_label.setObjectName("plate_txt_label")
        self.owner_name = QtWidgets.QPlainTextEdit(self.tab)
        self.owner_name.setGeometry(QtCore.QRect(20, 110, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.owner_name.setFont(font)
        self.owner_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);")
        self.owner_name.setObjectName("owner_name")
        self.plate_nbr_label = QtWidgets.QLabel(self.tab)
        self.plate_nbr_label.setGeometry(QtCore.QRect(30, 170, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.plate_nbr_label.setFont(font)
        self.plate_nbr_label.setStyleSheet("color: rgb(0, 255, 0);")
        self.plate_nbr_label.setObjectName("plate_nbr_label")
        self.plate_number_txt = QtWidgets.QPlainTextEdit(self.tab)
        self.plate_number_txt.setGeometry(QtCore.QRect(20, 230, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.plate_number_txt.setFont(font)
        self.plate_number_txt.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);")
        self.plate_number_txt.setObjectName("plate_number_txt")
        self.owner_contact_label = QtWidgets.QLabel(self.tab)
        self.owner_contact_label.setGeometry(QtCore.QRect(480, 50, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.owner_contact_label.setFont(font)
        self.owner_contact_label.setStyleSheet("color: rgb(0, 255, 0);")
        self.owner_contact_label.setObjectName("owner_contact_label")
        self.owner_contact = QtWidgets.QPlainTextEdit(self.tab)
        self.owner_contact.setGeometry(QtCore.QRect(470, 110, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.owner_contact.setFont(font)
        self.owner_contact.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);")
        self.owner_contact.setObjectName("owner_contact")
        self.add_information = QtWidgets.QPushButton(self.tab)
        self.add_information.setGeometry(QtCore.QRect(470, 230, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.add_information.setFont(font)
        self.add_information.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        self.add_information.setIcon(icon7)
        self.add_information.setIconSize(QtCore.QSize(60, 35))
        self.add_information.setObjectName("add_information")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1011, 471))
        self.tableWidget.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_18 = QtWidgets.QLabel(self.page_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_18.setObjectName("label_18")
        self.history_frame = QtWidgets.QFrame(self.page_4)
        self.history_frame.setGeometry(QtCore.QRect(10, 80, 1041, 481))
        self.history_frame.setStyleSheet("border:1px solid;\n"
"border-color: rgb(0, 255, 0);")
        self.history_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.history_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.history_frame.setObjectName("history_frame")
        self.time_heading = QtWidgets.QLabel(self.history_frame)
        self.time_heading.setGeometry(QtCore.QRect(150, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_heading.setFont(font)
        self.time_heading.setStyleSheet("color: rgb(0, 255, 0);")
        self.time_heading.setObjectName("time_heading")
        self.date_time_his = QtWidgets.QListWidget(self.history_frame)
        self.date_time_his.setGeometry(QtCore.QRect(150, 70, 241, 381))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.date_time_his.setFont(font)
        self.date_time_his.setStyleSheet("color: rgb(0, 255, 0);")
        self.date_time_his.setObjectName("date_time_his")
        item = QtWidgets.QListWidgetItem()
        self.date_time_his.addItem(item)
        self.number_plate_his = QtWidgets.QLabel(self.history_frame)
        self.number_plate_his.setGeometry(QtCore.QRect(410, 10, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.number_plate_his.setFont(font)
        self.number_plate_his.setStyleSheet("color: rgb(0, 255, 0);")
        self.number_plate_his.setObjectName("number_plate_his")
        self.plate_his_found = QtWidgets.QListWidget(self.history_frame)
        self.plate_his_found.setGeometry(QtCore.QRect(410, 70, 441, 381))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.plate_his_found.setFont(font)
        self.plate_his_found.setStyleSheet("color: rgb(0, 255, 0);")
        self.plate_his_found.setObjectName("plate_his_found")
        item = QtWidgets.QListWidgetItem()
        self.plate_his_found.addItem(item)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_19.setObjectName("label_19")
        self.frame_9 = QtWidgets.QFrame(self.page_5)
        self.frame_9.setGeometry(QtCore.QRect(10, 80, 1031, 481))
        self.frame_9.setStyleSheet("color: rgb(0, 255, 0);\n"
"border:1px solid rgba(0,255,0)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        
        self.userlist_list = QtWidgets.QListWidget(self.frame_9)
        self.userlist_list.setGeometry(QtCore.QRect(70, 80, 391, 371))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        self.userlist_list.setFont(font)
        self.userlist_list.setObjectName("userlist_list")
        item = QtWidgets.QListWidgetItem()
        self.userlist_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.userlist_list.addItem(item)
        self.users_list = QtWidgets.QLabel(self.frame_9)
        self.users_list.setGeometry(QtCore.QRect(70, 10, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.users_list.setFont(font)
        self.users_list.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.users_list.setFrameShape(QtWidgets.QFrame.Panel)
        self.users_list.setObjectName("users_list")
        self.users_list_email = QtWidgets.QLabel(self.frame_9)
        self.users_list_email.setGeometry(QtCore.QRect(480, 10, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.users_list_email.setFont(font)
        self.users_list_email.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.users_list_email.setFrameShape(QtWidgets.QFrame.Panel)
        self.users_list_email.setObjectName("users_list_email")
        self.userlist_list_email = QtWidgets.QListWidget(self.frame_9)
        self.userlist_list_email.setGeometry(QtCore.QRect(480, 80, 391, 371))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        self.userlist_list_email.setFont(font)
        self.userlist_list_email.setObjectName("userlist_list_email")
        item = QtWidgets.QListWidgetItem()
        self.userlist_list_email.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.userlist_list_email.addItem(item)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_20 = QtWidgets.QLabel(self.page_6)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_20.setObjectName("label_20")
        self.developer_frame = QtWidgets.QFrame(self.page_6)
        self.developer_frame.setGeometry(QtCore.QRect(10, 80, 1041, 481))
        self.developer_frame.setStyleSheet("border:1px solid;\n"
"border-color: rgb(0, 255, 0);")
        self.developer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.developer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.developer_frame.setObjectName("developer_frame")
        self.ahmed_descp = QtWidgets.QLabel(self.developer_frame)
        self.ahmed_descp.setGeometry(QtCore.QRect(160, 80, 341, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ahmed_descp.setFont(font)
        self.ahmed_descp.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);\n"
"padding:10px;")
        self.ahmed_descp.setWordWrap(True)
        self.ahmed_descp.setObjectName("ahmed_descp")
        self.saad_descp = QtWidgets.QLabel(self.developer_frame)
        self.saad_descp.setGeometry(QtCore.QRect(520, 80, 341, 231))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.saad_descp.setFont(font)
        self.saad_descp.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);\n"
"padding:10px;")
        self.saad_descp.setWordWrap(True)
        self.saad_descp.setObjectName("saad_descp")
        self.ahmed_name = QtWidgets.QLabel(self.developer_frame)
        self.ahmed_name.setGeometry(QtCore.QRect(180, 40, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ahmed_name.setFont(font)
        self.ahmed_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.ahmed_name.setAlignment(QtCore.Qt.AlignCenter)
        self.ahmed_name.setObjectName("ahmed_name")
        self.saad_name = QtWidgets.QLabel(self.developer_frame)
        self.saad_name.setGeometry(QtCore.QRect(540, 40, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.saad_name.setFont(font)
        self.saad_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.saad_name.setAlignment(QtCore.Qt.AlignCenter)
        self.saad_name.setObjectName("saad_name")
        self.project_descp = QtWidgets.QLabel(self.developer_frame)
        self.project_descp.setGeometry(QtCore.QRect(160, 330, 701, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_descp.setFont(font)
        self.project_descp.setStyleSheet("padding:10px;")
        self.project_descp.setWordWrap(True)
        self.project_descp.setObjectName("project_descp")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.setting_heading = QtWidgets.QLabel(self.page_7)
        self.setting_heading.setGeometry(QtCore.QRect(0, 10, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setting_heading.setFont(font)
        self.setting_heading.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.setting_heading.setFrameShape(QtWidgets.QFrame.Panel)
        self.setting_heading.setObjectName("setting_heading")
        self.frame_10 = QtWidgets.QFrame(self.page_7)
        self.frame_10.setGeometry(QtCore.QRect(0, 70, 1031, 481))
        self.frame_10.setStyleSheet("border:1px solid rgba(0,255,0);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setGeometry(QtCore.QRect(20, 20, 841, 431))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.current_pass = QtWidgets.QLabel(self.frame_11)
        self.current_pass.setGeometry(QtCore.QRect(20, 60, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.current_pass.setFont(font)
        self.current_pass.setStyleSheet("color: rgb(0, 255, 0);")
        self.current_pass.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.current_pass.setObjectName("current_pass")
        self.current_password = QtWidgets.QPlainTextEdit(self.frame_11)
        self.current_password.setGeometry(QtCore.QRect(20, 110, 311, 41))
        self.current_password.setObjectName("current_password")
        self.new_pass_txt = QtWidgets.QPlainTextEdit(self.frame_11)
        self.new_pass_txt.setGeometry(QtCore.QRect(20, 218, 311, 51))
        self.new_pass_txt.setObjectName("new_pass_txt")
        self.new_password = QtWidgets.QLabel(self.frame_11)
        self.new_password.setGeometry(QtCore.QRect(20, 170, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.new_password.setFont(font)
        self.new_password.setStyleSheet("color: rgb(0, 255, 0);")
        self.new_password.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.new_password.setObjectName("new_password")
        self.leaf_button_11 = QtWidgets.QPushButton(self.frame_11)
        self.leaf_button_11.setGeometry(QtCore.QRect(20, 310, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_button_11.setFont(font)
        self.leaf_button_11.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leaf_button_11.setIcon(icon8)
        self.leaf_button_11.setIconSize(QtCore.QSize(60, 35))
        self.leaf_button_11.setObjectName("leaf_button_11")
        self.stackedWidget.addWidget(self.page_7)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setGeometry(QtCore.QRect(40, 110, 311, 91))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.total_plates = QtWidgets.QLabel(self.frame_3)
        self.total_plates.setGeometry(QtCore.QRect(10, 10, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.total_plates.setFont(font)
        self.total_plates.setStyleSheet("color: rgb(0, 255, 0);")
        self.total_plates.setAlignment(QtCore.Qt.AlignCenter)
        self.total_plates.setObjectName("total_plates")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(360, 110, 321, 91))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.correct_results = QtWidgets.QLabel(self.frame_4)
        self.correct_results.setGeometry(QtCore.QRect(10, 10, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.correct_results.setFont(font)
        self.correct_results.setStyleSheet("color: rgb(0, 255, 0);")
        self.correct_results.setAlignment(QtCore.Qt.AlignCenter)
        self.correct_results.setObjectName("correct_results")
        self.frame_5 = QtWidgets.QFrame(self.page_2)
        self.frame_5.setGeometry(QtCore.QRect(690, 110, 331, 91))
        self.frame_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.incorrect_results = QtWidgets.QLabel(self.frame_5)
        self.incorrect_results.setGeometry(QtCore.QRect(30, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.incorrect_results.setFont(font)
        self.incorrect_results.setStyleSheet("color: rgb(0, 255, 0);")
        self.incorrect_results.setAlignment(QtCore.Qt.AlignCenter)
        self.incorrect_results.setObjectName("incorrect_results")
        self.frame_6 = QtWidgets.QFrame(self.page_2)
        self.frame_6.setGeometry(QtCore.QRect(40, 210, 311, 91))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.users = QtWidgets.QLabel(self.frame_6)
        self.users.setGeometry(QtCore.QRect(10, 10, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.users.setFont(font)
        self.users.setStyleSheet("color: rgb(0, 255, 0);\n"
"text-align:center;")
        self.users.setAlignment(QtCore.Qt.AlignCenter)
        self.users.setObjectName("users")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(360, 210, 321, 91))
        self.frame_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.frame_8 = QtWidgets.QFrame(self.page_2)
        self.frame_8.setGeometry(QtCore.QRect(690, 210, 331, 91))
        self.frame_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.counter = QtWidgets.QLabel(self.frame_8)
        self.counter.setGeometry(QtCore.QRect(30, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.counter.setFont(font)
        self.counter.setStyleSheet("color: rgb(0, 255, 0);")
        self.counter.setAlignment(QtCore.Qt.AlignCenter)
        self.counter.setObjectName("counter")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:     ")
        self.label_15.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_15.setObjectName("label_15")
        self.cam_frame = QtWidgets.QFrame(self.page_3)
        self.cam_frame.setGeometry(QtCore.QRect(10, 70, 1051, 481))
        self.cam_frame.setStyleSheet("")
        self.cam_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cam_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cam_frame.setObjectName("cam_frame")
        self.camera_stacks = QtWidgets.QStackedWidget(self.cam_frame)
        self.camera_stacks.setGeometry(QtCore.QRect(0, 60, 831, 421))
        self.camera_stacks.setStyleSheet("border:2px solid white;")
        self.camera_stacks.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_stacks.setObjectName("camera_stacks")
        self.detect_from_image = QtWidgets.QWidget()
        self.detect_from_image.setObjectName("detect_from_image")
        self.image_for_detection = QtWidgets.QLabel(self.detect_from_image)
        self.image_for_detection.setGeometry(QtCore.QRect(260, 10, 561, 391))
        self.image_for_detection.setObjectName("image_for_detection")
        self.browse_image = QtWidgets.QPushButton(self.detect_from_image)
        self.browse_image.setGeometry(QtCore.QRect(20, 120, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.browse_image.setFont(font)
        self.browse_image.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons/photo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_image.setIcon(icon9)
        self.browse_image.setIconSize(QtCore.QSize(60, 35))
        self.browse_image.setObjectName("browse_image")
        self.browse_image_2 = QtWidgets.QPushButton(self.detect_from_image)
        self.browse_image_2.setGeometry(QtCore.QRect(20, 190, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.browse_image_2.setFont(font)
        self.browse_image_2.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons/automation (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse_image_2.setIcon(icon10)
        self.browse_image_2.setIconSize(QtCore.QSize(60, 35))
        self.browse_image_2.setObjectName("browse_image_2")
        self.camera_stacks.addWidget(self.detect_from_image)
        self.detect_from_video = QtWidgets.QWidget()
        self.detect_from_video.setObjectName("detect_from_video")
        self.live_video_label = QtWidgets.QLabel(self.detect_from_video)
        self.live_video_label.setGeometry(QtCore.QRect(10, 10, 801, 391))
        self.live_video_label.setObjectName("live_video_label")
        self.camera_stacks.addWidget(self.detect_from_video)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.camera_stacks.addWidget(self.page_10)
        self.live_mode = QtWidgets.QPushButton(self.cam_frame)
        self.live_mode.setGeometry(QtCore.QRect(10, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.live_mode.setFont(font)
        self.live_mode.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../icons/broadcast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.live_mode.setIcon(icon11)
        self.live_mode.setIconSize(QtCore.QSize(60, 35))
        self.live_mode.setObjectName("live_mode")
        self.detect_from_image_2 = QtWidgets.QPushButton(self.cam_frame)
        self.detect_from_image_2.setGeometry(QtCore.QRect(190, 0, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.detect_from_image_2.setFont(font)
        self.detect_from_image_2.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detect_from_image_2.setIcon(icon12)
        self.detect_from_image_2.setIconSize(QtCore.QSize(60, 35))
        self.detect_from_image_2.setObjectName("detect_from_image_2")
        self.label_6 = QtWidgets.QLabel(self.cam_frame)
        self.label_6.setGeometry(QtCore.QRect(840, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.licence_number_plate = QtWidgets.QLabel(self.cam_frame)
        self.licence_number_plate.setGeometry(QtCore.QRect(840, 260, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.licence_number_plate.setFont(font)
        self.licence_number_plate.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.licence_number_plate.setFrameShape(QtWidgets.QFrame.Panel)
        self.licence_number_plate.setObjectName("licence_number_plate")
        self.cam_frame.raise_()
        self.label_15.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_31 = QtWidgets.QWidget()
        self.page_31.setObjectName("page_31")
        self.label_16 = QtWidgets.QLabel(self.page_31)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 1041, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);")
        self.label_16.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_16.setObjectName("label_16")
        self.anatomy_intro = QtWidgets.QPushButton(self.page_31)
        self.anatomy_intro.setGeometry(QtCore.QRect(130, 520, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.anatomy_intro.setFont(font)
        self.anatomy_intro.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../icons/id.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anatomy_intro.setIcon(icon13)
        self.anatomy_intro.setIconSize(QtCore.QSize(60, 35))
        self.anatomy_intro.setObjectName("anatomy_intro")
        self.anatomy_working = QtWidgets.QPushButton(self.page_31)
        self.anatomy_working.setGeometry(QtCore.QRect(340, 520, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.anatomy_working.setFont(font)
        self.anatomy_working.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        self.anatomy_working.setIcon(icon10)
        self.anatomy_working.setIconSize(QtCore.QSize(60, 35))
        self.anatomy_working.setObjectName("anatomy_working")
        self.anatomy_limit = QtWidgets.QPushButton(self.page_31)
        self.anatomy_limit.setGeometry(QtCore.QRect(560, 520, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.anatomy_limit.setFont(font)
        self.anatomy_limit.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(0, 255, 0);")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../icons/garden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anatomy_limit.setIcon(icon14)
        self.anatomy_limit.setIconSize(QtCore.QSize(60, 35))
        self.anatomy_limit.setObjectName("anatomy_limit")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_31)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 80, 1041, 431))
        self.stackedWidget_2.setStyleSheet("border-color: rgb(0, 255, 0);\n"
"border:1px solid;\n"
"border-color: rgb(0, 255, 0);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.Into_page = QtWidgets.QWidget()
        self.Into_page.setObjectName("Into_page")
        self.intro_heading = QtWidgets.QLabel(self.Into_page)
        self.intro_heading.setGeometry(QtCore.QRect(0, 0, 1021, 421))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.intro_heading.setFont(font)
        self.intro_heading.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"padding:10px;")
        self.intro_heading.setWordWrap(True)
        self.intro_heading.setObjectName("intro_heading")
        self.stackedWidget_2.addWidget(self.Into_page)
        self.Working_Page = QtWidgets.QWidget()
        self.Working_Page.setObjectName("Working_Page")
        self.label_8 = QtWidgets.QLabel(self.Working_Page)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.working_heading = QtWidgets.QLabel(self.Working_Page)
        self.working_heading.setGeometry(QtCore.QRect(10, -20, 1021, 441))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.working_heading.setFont(font)
        self.working_heading.setStyleSheet("color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);\n"
"padding:10px;\n"
"border-color:black;\n"
"font-size:14px;")
        self.working_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.working_heading.setWordWrap(True)
        self.working_heading.setObjectName("working_heading")
        self.stackedWidget_2.addWidget(self.Working_Page)
        self.Limit_Page = QtWidgets.QWidget()
        self.Limit_Page.setObjectName("Limit_Page")
        self.limit_heading = QtWidgets.QLabel(self.Limit_Page)
        self.limit_heading.setGeometry(QtCore.QRect(20, 20, 1011, 401))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.limit_heading.setFont(font)
        self.limit_heading.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 0);\n"
"padding:10px;")
        self.limit_heading.setWordWrap(True)
        self.limit_heading.setObjectName("limit_heading")
        self.stackedWidget_2.addWidget(self.Limit_Page)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.stackedWidget_2.addWidget(self.page_15)
        self.stackedWidget.addWidget(self.page_31)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        self.camera_stacks.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automatic Licence Number Plate Detection And Recognition"))
        self.leaf_button_2.setText(_translate("MainWindow", "CAMERA ON"))
        self.leaf_button_3.setText(_translate("MainWindow", " PLATES"))
        self.leaf_button_4.setText(_translate("MainWindow", "HISTORY"))
        self.leaf_button_5.setText(_translate("MainWindow", "USERS"))
        self.leaf_button_6.setText(_translate("MainWindow", "LOGOUT"))
        self.leaf_button_7.setText(_translate("MainWindow", "ANATOMY"))
        self.leaf_button_8.setText(_translate("MainWindow", "SETTINGS"))
        self.leaf_button_9.setText(_translate("MainWindow", "DASHBOARD"))
        self.leaf_button_10.setText(_translate("MainWindow", "DEVS"))
        self.label.setText(_translate("MainWindow", "Automatic Licence Number Plate Detection And Recognition "))
        self.label_17.setText(_translate("MainWindow", "SAVED NUMBER PLATES"))
        self.plate_txt_label.setText(_translate("MainWindow", "Plate Owner Name"))
        self.plate_nbr_label.setText(_translate("MainWindow", "Plate Number"))
        self.owner_contact_label.setText(_translate("MainWindow", "Owner Contact"))
        self.add_information.setText(_translate("MainWindow", "Add Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Add New Plate"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Plate Number"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Owner Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Plate Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contact"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "HWL"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "HELLO"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Saved Number Plates"))
        self.label_18.setText(_translate("MainWindow", "RECOGNIZING HISTORY"))
        self.time_heading.setText(_translate("MainWindow", "Date/Time"))
        __sortingEnabled = self.date_time_his.isSortingEnabled()
        self.date_time_his.setSortingEnabled(False)
        item = self.date_time_his.item(0)
        item.setText(_translate("MainWindow", "sadalk"))
        self.date_time_his.setSortingEnabled(__sortingEnabled)
        self.number_plate_his.setText(_translate("MainWindow", "Plate Detected"))
        __sortingEnabled = self.plate_his_found.isSortingEnabled()
        self.plate_his_found.setSortingEnabled(False)
        item = self.plate_his_found.item(0)
        item.setText(_translate("MainWindow", "EF-2223"))
        self.plate_his_found.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("MainWindow", "USERS"))
        __sortingEnabled = self.userlist_list.isSortingEnabled()
        self.userlist_list.setSortingEnabled(False)
        item = self.userlist_list.item(0)
        item.setText(_translate("MainWindow", "Hello World"))
        item = self.userlist_list.item(1)
        item.setText(_translate("MainWindow", "Email@gmail.com"))
        self.userlist_list.setSortingEnabled(__sortingEnabled)
        self.users_list.setText(_translate("MainWindow", "NAMES"))
        self.users_list_email.setText(_translate("MainWindow", "EMAILS"))
        __sortingEnabled = self.userlist_list_email.isSortingEnabled()
        self.userlist_list_email.setSortingEnabled(False)
        item = self.userlist_list_email.item(0)
        item.setText(_translate("MainWindow", "Hello World"))
        item = self.userlist_list_email.item(1)
        item.setText(_translate("MainWindow", "Email@gmail.com"))
        self.userlist_list_email.setSortingEnabled(__sortingEnabled)
        self.label_20.setText(_translate("MainWindow", "DEVELOPERS GLIMPSES"))
        self.ahmed_descp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CS FINAL YEAR STUDENT</p><p align=\"center\">Has been Working as a Graphic Designer from 2 Years </p><p align=\"center\">Skills : Adobe Illustrate,Adobe Photoshop,Web Development,Video Editing,WordPress</p></body></html>"))
        self.saad_descp.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CS FINAL YEAR STUDENT</p><p align=\"center\">Has been Working as a Graphic Designer from 2 Years </p><p align=\"center\">Skills : Adobe Illustrate,Adobe Photoshop,Web Development,Video Editing,WordPress</p></body></html>"))
        self.ahmed_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#00ff00;\">AHMED ALI</span></p></body></html>"))
        self.saad_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#00ff00;\">SAAD UL HAQ</span></p></body></html>"))
        self.project_descp.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt; color:#00ff00;\">This project is completed as in &quot;</span><span style=\" font-size:12pt; font-weight:600; color:#00ff00;\">Final Year Project&quot;,</span><span style=\" font-size:12pt; color:#00ff00;\">the main functionality of this application is to detect Vehicle Licence Number Plate whether it come from an image or a video. it\'s utilized the OpenCv library for image processing,and KNN for better character recognition.it has the functionlity to detect Vehilce Licence Number Plate whether it come from image or video. </span></p></body></html>"))
        self.setting_heading.setText(_translate("MainWindow", "SETTINGS"))
        self.current_pass.setText(_translate("MainWindow", "Current Password"))
        self.new_password.setText(_translate("MainWindow", "New Password"))
        self.leaf_button_11.setText(_translate("MainWindow", "CHANGE PASSWORD"))
        self.label_7.setText(_translate("MainWindow", "DASHBOARD"))
        self.total_plates.setText(_translate("MainWindow", "PLATES 44"))
        self.correct_results.setText(_translate("MainWindow", "CORRECT 44"))
        self.incorrect_results.setText(_translate("MainWindow", "INCORRECT 45"))
        self.users.setText(_translate("MainWindow", "USERS 3"))
        self.label_13.setText(_translate("MainWindow", "EEEEEEEEEEEEEE00"))
        self.counter.setText(_translate("MainWindow", "COUNTER 444"))
        self.label_15.setText(_translate("MainWindow", "CAMERA ON"))
        self.image_for_detection.setText(_translate("MainWindow", "TextLabel"))
        self.browse_image.setText(_translate("MainWindow", "BROWSE IMAGE"))
        self.browse_image_2.setText(_translate("MainWindow", "DETECT NUMBER"))
        self.live_video_label.setText(_translate("MainWindow", "TextLabel"))
        self.live_mode.setText(_translate("MainWindow", "LIVE MODE"))
        self.detect_from_image_2.setText(_translate("MainWindow", "DETECT FROM IMAGE"))
        self.label_6.setText(_translate("MainWindow", "LICENCE PLATE"))
        self.licence_number_plate.setText(_translate("MainWindow", "EE-0345"))
        self.label_16.setText(_translate("MainWindow", "SYSTEM ANATOMY"))
        self.anatomy_intro.setText(_translate("MainWindow", "INTRODUCTION"))
        self.anatomy_working.setText(_translate("MainWindow", "WORKING"))
        self.anatomy_limit.setText(_translate("MainWindow", "LIMITATIONS"))
        self.intro_heading.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">The world is changing so rapidly,and technology has palyed its role significantly to empowering and create eases in human lifes ,from medical to telecommunications every thing has changed and become more reliable.Timing has become more precious and priceless for everyone,because if it\'s late,then it might cost you a alot in any manner.Computer Vision has the capablities and solved humans most common problems.Computer Vision is the way to mimic and behave like human vision,how we precieve through eye,the most important how we recognizing things.We human interpret object through differents ways like to detect edges and many more.</p><p align=\"justify\">This System is based on Computer Vision and made for detecting and recognizing Vehicles Licence Number Plate,Detecting and recognizing number plate is pretty tough job in computer vision,correctly and accuratly detection of number plate is somehow depends on image and angle of Licence Plate placement on vehicle.</p><p align=\"justify\">This System has the abality to operate on two differents modes </p><p align=\"justify\">Detect Licence Number from image </p><p align=\"justify\">The second one is more important,which is detect Licence Number through live video footage.</p><p align=\"justify\"><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "INTRODUCTION"))
        self.working_heading.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semilight\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">This working of this system is very simple and understandable,first and the most image acquiring the image or detect scene in video,then image has preproccessed for further actions.The Preprocessed image now converting into greyscale,after that we detect countours in image and by the used of KNN methods we can further look into image to detect the position of Licence Number plate in given image.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Grayscaling is the process of converting an image from other color spaces e.g RGB, CMYK, HSV, etc. to shades of gray. It varies between complete black and complete white.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Contours can be explained simply as a curve joining all the continuous points (along the boundary), having same color or intensity. The contours are a useful tool for shape analysis and object detection and recognition.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">K-nearest neighbors Algorithm</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">The KNN is the simplest supervised learning algorithm in Machine Learning,KNN assumes the similirity between new data and available data,and put new data data into its nearest category .KNN is lazy learner algorithm,this means it does not learn immediately from data.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">How we use KNN in this project ?</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">In this project we used knn for detecting possible character,then classify that data into relavant category, and alogirthm tries to fetch accurate number plate from given image or scene.</span></p></body></html>"))
        self.limit_heading.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">This system has some limitations,first this is mixture of computer vison and ML algorithm so achieving high accuracy is not an easy job, and second limitation system has, to expose every time to new style and size with differernt typography number plate,so its became hard to detect correct number plate number, In our scanario we have achieved 70% correct detection with different images .</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
